FROM webhippie/alpine:latest-arm32v6

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Reg" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/reg"]

RUN apk update && \
  apk upgrade && \
  rm -rf /var/cache/apk/*

RUN wget -q -O /usr/bin/reg https://github.com/genuinetools/reg/releases/download/v0.16.0/reg-linux-arm && \
  chmod +x /usr/bin/reg
